### ISSUE TITLE
Easy way to add currently playing song to playlist

### ISSUE THREAD

**Issue by count-null** [UnicornsOnLSD/finamp#108]
To add a song to playlist, you have to find it in the main list (or search for it). 90% of the time I want to add a song, it's because it's currently playing. 

Great work all! This is the best mobile streaming app I've ever used for self hosted libraries.

**Comment by UnicornsOnLSD** [comment]
Added a button on the player screen in 878f2b66b0c6049a88075bf9b76114775cabe55a
