### ISSUE TITLE
Can't playback .oga files with opus encoding on IOS

### ISSUE THREAD

**Issue by michaelharmonart** [UnicornsOnLSD/finamp#109]
I would hope it's possible to either, support server side audio transcoding, or support opus in an oga container.

**Comment by UnicornsOnLSD** [comment]
iOS doesn't support OPUS files unless they're in a .caf container. For now, you could enable transcoding when you play OPUS songs. I'm going to look into automatic transcoding for the next release.

**Comment by UnicornsOnLSD** [comment]
Gonna close this for the same reason as #124. It's currently an issue with Apple as they do not properly support Opus/Vorbis. This may be fix if the audio plugin I'm using gets LibVLC support, which it may do in the near future.
