### ISSUE TITLE
Unable to play playlist

### ISSUE THREAD

**Issue by sambhavsaggi** [UnicornsOnLSD/finamp#112]
I am on iOS 14.7.1 running FinAmp from the App store. When playing an M3U playlist from Jellyfin, it does not play but rather gives me this error:

```
[AudioServiceHelper/SEVERE] 2021-08-23 18:31:00.615417: RangeError (index): Invalid value: Valid value range is empty: 0

null
```

This error has not occurred before (no updates, etc) and every song in the playlist can be played from the app. Other clients have no issue with the playlist either.

**Comment by UnicornsOnLSD** [comment]
Can you try again and copy your main thread logs?

**Comment by sambhavsaggi** [comment]
Logs: https://ghostbin.com/paste/JhQD2

**Comment by UnicornsOnLSD** [comment]
Could you try redownloading the playlist? Something may have not downloaded correctly. Also test streaming the playlist while you're at it

**Comment by sambhavsaggi** [comment]
There has to be an easier way to delete all downloads...

Anyway, it seems like streaming is working. After downloading all of the songs in the playlist, one had failed repeatedly. However, the rest of the playlist plays fine now.

The failed download appears to have been from a 404. I'll do some digging and figure out if this is a Jellyfin or FinAmp issue. Thanks for the help!

**Comment by UnicornsOnLSD** [comment]
Glad to hear that you've (sort of) solved it. Let me know if you find anything :)
