### ISSUE TITLE
bug: downloads are falsely synced across phones

### ISSUE THREAD

**Issue by dpraul** [UnicornsOnLSD/finamp#118]
Hey there! I just got a new phone and encountered a bug after migrating. It appears that the downloaded songs were synced to my new device, but there is no way to resync the actual audio files. All the downloads from my prior phone were marked as "completed", with no way to redownload them, and no easy way to clear the status except one-by-one.

I resolved this by clearing all app data and manually redownloading my files, but I'm sure there are more elegant ways to handle this.

**Comment by UnicornsOnLSD** [comment]
Downloads and stuff are currently stored in the app's downloads folder, which is backed up to iCloud by default. I'm looking into changing the default downloads location to the proper place, so that this doesn't keep happening.

**Comment by dpraul** [comment]
I should've clarified that this was going from Android to Android, but sounds like it's the same issue. Not a huge one, though - app is fantastic! :)

**Comment by UnicornsOnLSD** [comment]
Fixed in 8ec68e8 and 7bddd46
