### ISSUE TITLE
404 on track download

### ISSUE THREAD

**Issue by kernitus** [UnicornsOnLSD/finamp#120]
When trying to download songs I keep receiving this error in the log:

`[Flutter/SEVERE] 2021-08-31 21:50:07.665936: HttpException: Invalid statusCode: 404, uri = BASEURL/Items/263310fb7cc8fcc2d56f6e7b7f93294a/Images/Primary?format=webp&MaxWidth=147&MaxHeight=147`

However obviously the connection to the server works, because I can play the song in the app just fine. Downloads also work on a different device without a problem.

**Comment by UnicornsOnLSD** [comment]
That error is an image failing to load, it doesn't have anything to do with downloading. Are the downloads failing?

**Comment by kernitus** [comment]
Yeah, the get stuck in the purgatory of being in the download list with 0 bytes downloaded, as if they never actually start

**Comment by UnicornsOnLSD** [comment]
Could you try again and copy all of your logs?

**Comment by NovaMoon** [comment]
Having the same error

`[Flutter/SEVERE] 2021-09-03 01:13:34.917023: HttpException: Invalid statusCode: 404, uri = BASEURL/Items/ac541763e0fee5c3e548ea7ae474364b/Images/Primary?format=webp&MaxWidth=147&MaxHeight=147`

Im seeing this error aswell
`[Flutter/SEVERE] 2021-09-03 01:13:54.874727: Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1108)
#1      _DownloadedIndicatorState.initState.<anonymous closure> (package:finamp/components/AlbumScreen/DownloadedIndicator.dart:43)
#2      _rootRunUnary (dart:async/zone.dart:1370)
#3      _CustomZone.runUnary (dart:async/zone.dart:1265)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#6      _DelayedData.perform (dart:async/stream_impl.dart:591)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663)
#9      _rootRun (dart:async/zone.dart:1346)
#10     _CustomZone.run (dart:async/zone.dart:1258)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1162)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202)
#13     _rootRun (dart:async/zone.dart:1354)
#14     _CustomZone.run (dart:async/zone.dart:1258)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1162)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)`

**Comment by UnicornsOnLSD** [comment]
As I said, the "Invalid statusCode: 404" error is just an image failing to load. The second error is interesting though, something is going wrong when updating the download indicator widget. If you can, try again and use the "copy logs" icon button on the top right to copy everything (you may have to put them on pastebin or something).

By the way, the downloader won't start if you're really low on storage. If you're not low on storage, could you try uninstalling and resintalling the app? Something may have broken the downloads database.

**Comment by kernitus** [comment]
Ok reinstalling didn't change much - but I figured out that when using a custom directory it doesn't download, when using the internal storage it does.

**Comment by UnicornsOnLSD** [comment]
Ah, that's OK then. Using custom directories is a bit jank because of Android, you could use the "App Directory" option if you want to store songs on an SD card.

**Comment by NovaMoon** [comment]
How can i get the log to you without posting it here since i feel uncomfortable doing so (its having identifiers in it)

**Comment by UnicornsOnLSD** [comment]
It sensors the base URL by default, and tokens are truncated so it should be fine. You could email me (on my profile) if you still don't want to send it on Github

**Comment by NovaMoon** [comment]
> It censors the base URL by default, and tokens are truncated so it should be fine. You could email me (on my profile) if you still don't want to send it on Github

The base url wasnt censored in the blue log sections.

ok so i reinstalled the app and downloaded my playlist again, this time it completed the downloads without fail.

The logs are spammed with the errors i posted above, so much that copying everything wont let me paste it at all. I guess i hit some clipboard limit?

I think what caused the error before was that i stopped the downloads before by going into offline mode while it was syncing and that perhaps broke the database or that power savings kicked in and stopped it because this time my phone was on the whole time.

**Comment by UnicornsOnLSD** [comment]
Yeah, you probably broke the DB somehow, it happens lol

Clipboard limits are an issue, both the OS and any text field doesn't expect megabytes of text to be thrown into the clipboard.

**Comment by UnicornsOnLSD** [comment]
Considering this closed since it seems to be Android bugs and something breaking randomly

**Comment by kernitus** [comment]
Alright.. However I would like to say that I _tried_ to copy the log, but it crashed any app I tried to paste it into. Perhaps saving it as a file might be better?

**Comment by Y0ngg4n** [comment]
Same issue here :(

**Comment by UnicornsOnLSD** [comment]
Do you use a custom directory as your download location?

**Comment by Y0ngg4n** [comment]
@UnicornsOnLSD yes

**Comment by UnicornsOnLSD** [comment]
Custom directories can be buggy as Flutter (the framework I use to make Finamp) doesn't really handle directories in the way that Android wants. If you're using a custom directory to store songs on an SD card, I recommend you use the App Directory option in the download location settings. There's a bit of text that tells you how to tell which option is your SD card.
