### ISSUE TITLE
Ogg vorbis playback is silent on IOS

### ISSUE THREAD

**Issue by michaelharmonart** [UnicornsOnLSD/finamp#124]
Would love to play my ogg files, they playback in the main jellyfin app.

**Comment by UnicornsOnLSD** [comment]
I'll look into it. Have you tried any other albums?

**Comment by michaelharmonart** [comment]
They were ripped and encoded by me with fre:ac, if that's any help. So no I have no examples of ogg files that are working.

**Comment by UnicornsOnLSD** [comment]
It looks like iOS doesn't natively support Vorbis. The main Jellyfin app might use another library for audio playback. There isn't really anything I can do about it since I don't have the necessary iOS development skills to implement another library, so I'm closing this issue.
