### ISSUE TITLE
Playback restarts when buffering

### ISSUE THREAD

**Issue by ShiniGandhi** [UnicornsOnLSD/finamp#131]
Whenever streaming a song and it stops for buffering, once it gets some more buffer, the song starts from the beginning again.

**Comment by UnicornsOnLSD** [comment]
What platform are you on, and what format is your music?

**Comment by ShiniGandhi** [comment]
> What platform are you on, and what format is your music?

Android 11, mainly FLACs, but I'm transcoding everything.

**Comment by UnicornsOnLSD** [comment]
Transcoding is a bit jank in the current release (seeking and stuff like that doesn't work) but the next release will be much better.

**Comment by screwfaze** [comment]
> Transcoding is a bit jank in the current release (seeking and stuff like that doesn't work) but the next release will be much better.

Really looking forward to the next release, been using finamp everyday and it's 👌

**Comment by ncoschrdr** [comment]
Hi, is there an update on this? I'm using iOS and the stream randomly restarts mid-track when using transcoding (probably the same issue that Shini has). Nice app btw!

**Comment by UnicornsOnLSD** [comment]
The fix for this is currently in master, will be in the next release. Forgot to close this issue :)
