### ISSUE TITLE
Can  using libmpv support video playback

### ISSUE THREAD

**Issue by zdabing** [UnicornsOnLSD/finamp#132]
Can using libmpv support video playback

**Comment by UnicornsOnLSD** [comment]
I considered adding video support to Finamp a while ago, but I've decided that it's out of the scope of the app.

**Comment by Extarys** [comment]
For what it's worth, I would prefer a very nice, feature rich music app than an all in one, can do it all, half baked app.

For video there is findroid, or the official jellyfin app.

**Comment by UnicornsOnLSD** [comment]
Agreed, that's why I decided not to do it. The Jellyfin Android app may be getting MPV playback anyway (https://github.com/jellyfin/jellyfin-androidtv/pull/1046). On the iOS side, Swiftfin uses libvlc, which is about as good as you can get on iOS.
