### ISSUE TITLE
A new iOS release, please?

### ISSUE THREAD

**Issue by Liarra** [UnicornsOnLSD/finamp#139]
The current release in AppStore is 2 months old. 
As an iOS user, I would like to receive the latest features and bugfixes.

**Comment by mdillavou** [comment]
I had a similar error. It was due to having the 'Star' clicked. Unclicking the 'Star' (between the Sort and Search) resolved it for me.

**Comment by stefan1983** [comment]
Maybe put the current test versions online on apple TestFlight?

**Comment by UnicornsOnLSD** [comment]
I'm so close to release now that there's no point. I've considered setting up a thing to put the master branch on Testflight, but stuff breaks a lot in the master branch and I don't really have stable points to make a Testflight build.

**Comment by SwatsonCodes** [comment]
gentle bump, would love to see a new ios release!

**Comment by UnicornsOnLSD** [comment]
I'm nearly done with downloading images, once that's done I can pretty much start preparing for the next release

**Comment by UnicornsOnLSD** [comment]
Released :)
