### ISSUE TITLE
Display track artist instead of album artist

### ISSUE THREAD

**Issue by carks32** [UnicornsOnLSD/finamp#152]
Since the last.fm scrobble part of the app is kind of not working right now (dont know if it will work just fine next update), I started to not scrobble on jellyfin itself but on my phone with an external scrobbler and it works just fine. But [certain records](https://musicbrainz.org/release/460c43b3-7b72-484a-b9dc-223c4aaf5644) are a compilation of [various artists](https://musicbrainz.org/release/12ad490b-6a3b-4315-9f4f-fc3f04c041c6) and it just doesn't display the track artist on the app, just "Various Artists". If you don't mind, would you be able to change this?

**Comment by rom4nik** [comment]
I've already fixed this in #116, but an update containing this change hasn't been released yet.

![Screenshot_20211128-230754_Finamp](https://user-images.githubusercontent.com/46846000/143788022-69a9bdcb-d601-4742-b087-831019ba533d.png)
![Screenshot_20211128-230857_Finamp](https://user-images.githubusercontent.com/46846000/143788023-5e69c975-a67f-4276-84b8-1d58f3f4b0f0.png)

**Comment by carks32** [comment]
I'm blind, didn't see that. Thanks a lot tho
