### ISSUE TITLE
Does iOS and Android both have the same features?

### ISSUE THREAD

**Issue by Extarys** [UnicornsOnLSD/finamp#154]
For clients comparison [here](https://github.com/basings/selfhosted-music-overview/pull/91#issuecomment-986037350) we would like to make sure both iOS and Android have the same features.

If not, can we get a list of limitation/features difference?

I do not own an iOS device to take a look.
Thanks for your time

**Comment by UnicornsOnLSD** [comment]
Hi, iOS and Android have feature parity, everything works on both platforms. The only "exception" I can think of is that iOS doesn't support OPUS/Vorbis, but that's a limitation of iOS's built-in media playback functionality. selfhosted-music-overview looks like a great list by the way, thanks for including me in it :)

**Comment by Extarys** [comment]
Hey @UnicornsOnLSD Thanks for your reply and your great work - this is my go-to Jellyfin music player ever since it came out :heart: . (Hope school doesn't exhaust you too much, take care)

**Comment by UnicornsOnLSD** [comment]
Thanks, uni is a bit exhausting (see the commit frequency since September) but I'm doing fine and I can still work on Finamp when I feel like it. It probably doesn't help that I've left all the hard stuff to the end of this release though 🙃

**Comment by Extarys** [comment]
Hey no worries, still very excited to get a new release but I know it'll eventually come together. The important part right now is sleep :smile:

I wish I could help but Android development looks more complicated than Assembly to me :joy:
