### ISSUE TITLE
Proposing essential buttons in horizontal view

### ISSUE THREAD

**Issue by Eothred** [UnicornsOnLSD/finamp#155]
Thank you for developing and maintaining this application! Having an option to get offline sync from my Jellyfin server has been very very welcome :)

I am on Android, version 0.5.1 on Samsung S20.

I often use Finamp in offline mode in the car, where it is displaying horizontally because the phone is mounted with navigation open. I noticed that the Finamp horizontal view only shows the album art and song information, without any navigation buttons. I was thinking that at least pause/play, and prev/next buttons could be useful here, but I suppose this depends a bit on how the application is intended to be used.

**Comment by UnicornsOnLSD** [comment]
This was mostly fixed a while ago, but it still isn't perfect. I might make it so that the album art is either to the side or just not there when landscape.

![image](https://user-images.githubusercontent.com/44349936/144999051-03f26451-dc56-4488-ab03-c5512bd3a1c8.png)

**Comment by Maxplosion** [comment]
Putting the cover to the e.g. right side and having the controlls on the other might be the best for most modern resolution phones. (narrow and high).
Don't know about very small ones though.
Input from my side, current version works good on a Fold, I like the large covers a lot.

**Comment by Eothred** [comment]
Huh, interesting, is that the same version I use? I attach my screenshot below. If same version, maybe because screen ratio is different on S20?

I second @Maxplosion suggestion of maybe having buttons on the right and coverart on the left. Alternatively buttons on bottom as now, but song information next to coverart instead of below it. New phones tend to indeed be very narrow.

![Screenshot_20211209-090034](https://user-images.githubusercontent.com/187567/145357828-b8837b13-e69b-4a1a-bfe7-a47366673692.jpg)

**Comment by Maxplosion** [comment]
I've just checked on my front display in landscape and yes, same issue as Eothred here, there are no controls, only the cover, track/artist and the seekbar and 1/3 of the runtime/length text.

**Comment by UnicornsOnLSD** [comment]
This was fixed a while ago during 0.6 development, although a proper landscape GUI will be made at some point in the future
