### ISSUE TITLE
[FR] Combine artist and album view

### ISSUE THREAD

**Issue by basings** [UnicornsOnLSD/finamp#164]
Current behavior: if you click on an artist you can see all albums. If you then click on an album you see one album. You could combine them. So that there is the artist at the top in the artist view with albums below that. If you click on an album it drops down a list of songs. You'd have a much better/seemless browsing experience. 

![Screenshot_20211222_103708_com unicornsonlsd finamp_1](https://user-images.githubusercontent.com/92867705/147071186-31767a09-8498-463d-b50e-53b7a3eaa2cd.jpg)
![Screenshot_20211222_103704_com unicornsonlsd finamp_1](https://user-images.githubusercontent.com/92867705/147071193-fce7ca96-8a7d-4b06-b3e9-223e6c6c339e.jpg)

**Comment by UnicornsOnLSD** [comment]
I think this would look a bit awkward on a phone, although it could work on desktop. I'll close this issue for now, but when I'm looking into Finamp's tablet/desktop UI I'll keep your idea in mind :)
