### ISSUE TITLE
Declare "APP_MUSIC" in AndroidManifest 

### ISSUE THREAD

**Issue by J4gQBqqR** [UnicornsOnLSD/finamp#166]
Can this app declare "android.intent.category.APP_MUSIC" category in AndroidManifest? It is unrecognized by some other apps on system as default music player.

**Comment by UnicornsOnLSD** [comment]
From https://developer.android.com/reference/android/content/Intent#CATEGORY_APP_MUSIC:

> The activity should be able to play, browse, or manipulate music files stored on the device.

Would that really make sense for Finamp? It's not intended to be a replacement for something like VLC.

**Comment by J4gQBqqR** [comment]
Well, if taking it at face value, it is what's described.

But we should also add to this line with the fact that in real life, some apps, widgets, Bluetooth controls relies on this declaration to handover the correct intent action.

At the end of the day, it depends on your (developers') view to see if you want to implement it or not.

**Comment by UnicornsOnLSD** [comment]
Added in dc878e4, if it causes any issues it won't be hard to change back :)
