### ISSUE TITLE
Compatible - Android TV

### ISSUE THREAD

**Issue by AussieAbroad** [UnicornsOnLSD/finamp#167]
Any plans to create Android/Google TV version

**Comment by UnicornsOnLSD** [comment]
No, there isn't much point since the Jellyfin Android TV client can play music, and from my experience it's a great client.

**Comment by motlaghreyhan** [comment]
I commented on an old reddit post, but in case that goes unseen, I'm going to mention it in this issue too: 

I can't find a decent android tv client that supports gapless playback, if you were able to fix the clicking on things issue, it would be phenomenal. And maybe the only app of its kind. It wouldn't be quite as polished as a made for TV app, but if it's fully controllable from the remote that would be all I ask.

**Comment by Djarid** [comment]
I've got this working on my Shield TV but the lack of tiles makes it unworkable as a 1st class solution.
I investigated finamp cue to music search issues in the jellyfin app.

**Comment by Chaphasilor** [comment]
So the problem is that the currently selected/hovered element isn't being highlighted? That sounds fixable...
