### ISSUE TITLE
Connection problem: NoSuchMethodError: The method 'call' was called on null.

### ISSUE THREAD

**Issue by foss-** [UnicornsOnLSD/finamp#175]
iOS 15.2
Finamp 0.5.1

Curiously this worked fine previously. I signed out and back in to find the error was persisting. Since there was no update for Finamp recently I am unsure what is causing this. On a second iOS 15.2 device Finamp works just fine.

Offline Mode works as expected, but online mode runs into this error.

```
[Flutter/SEVERE] 2022-01-12 12:58:34.780601: NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call(Instance of 'Response<dynamic>')

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:97)
#2      _MusicScreenTabViewState._getPage (package:finamp/components/MusicScreen/MusicScreenTabView.dart:107)
<asynchronous suspension>
```

**Comment by UnicornsOnLSD** [comment]
That error is unrelated (and I'm not entirely sure what's failing as everything keeps working when it comes up for me). Could you copy all of your logs? You can do it with the button at the top of the logs screen. Your server URL and token will be censored, so it should be safe to share here.

**Comment by foss-** [comment]
@UnicornsOnLSD https://bin.disroot.org/?b9d7c155cc7d71ee#5YFwddPSWUWwSsM4rPW9CPEWNfJK4BaJyYwT1WeeyKhJ
(one day, so pelase create a local copy if there is anything useful in the log)

**Comment by UnicornsOnLSD** [comment]
Looks like you're getting HTTP 500 on some requests (specifically getting AlbumArtists). HTTP 500 means something went wrong on the server side. Do you see any errors in your Jellyfin logs?

Also, I'll see if I can make the log copy button share a file instead, other people have mentioned that their phones don't like copying that much text

**Comment by UnicornsOnLSD** [comment]
Oh actually I can see that you have favourites enabled in the logs. Favourites is broken in the artists view right now (should have probably disabled the button lol). If you have it enabled, you can disable it by tapping the star button at the top of the main screen.

**Comment by foss-** [comment]
Spot on, I hadn't even noticed this option was active, but you are abolutely right. Follow-up: https://github.com/UnicornsOnLSD/finamp/issues/176

Thanks for digging and finding the cause for the trouble.
