### ISSUE TITLE
[question] DSF support

### ISSUE THREAD

**Issue by J4gQBqqR** [UnicornsOnLSD/finamp#179]
Hi, sorry if I asked in the wrong place, does the Android client support DSF playback?

Please close the issue at your convenience.

Thank you.

**Comment by UnicornsOnLSD** [comment]
Sorry for not seeing this - DSF is not supported in ExoPlayer, so it won't work in Finamp. I'm considering trying different player backends to support more codecs, this is being discussed at #177
