### ISSUE TITLE
[Feature Request] Date Added Filter

### ISSUE THREAD

**Issue by seniorm0ment** [UnicornsOnLSD/finamp#181]
Requesting the ability to sort by Date Added, so you can easily see newly imported albums and songs.

**Comment by UnicornsOnLSD** [comment]
You can do this with the "Date Created" filter in the sort options. There was another issue that pointed out that this was hard to find, so it's been renamed to Date Added for the next release

**Comment by seniorm0ment** [comment]
Isn't Date Created and Date Added two different things'

**Comment by UnicornsOnLSD** [comment]
No, "Date Created" is just what the Jellyfin API calls it. When you sort by "Date Added" in the web interface, the "DateCreated" sort option is used in the API.

**Comment by seniorm0ment** [comment]
Ah ok, thanks
