### ISSUE TITLE
Playback breaks in iOS when transcoded from Flac

### ISSUE THREAD

**Issue by arvidortwig** [UnicornsOnLSD/finamp#187]
Hi, on my iOS 15 device with the latest finamp (0.5.1) when i am transcoding from Flac to AAC the song reproducably restarts at the Middle or the first 1/3. It seems like the song doesn't gets loaded fully when transcoded. 
On Android everything is working fine with transcoding and also if i dont transcode on iOS the songs play until the end. Reinstalled the app, issue stays...

**Comment by UnicornsOnLSD** [comment]
This is likely an issue with how transcoding works in the current release. In the next release, transcoding will use HLS so it should break less (and you'll actually be able to seek).

**Comment by UnicornsOnLSD** [comment]
Closing as HLS playback has been implemented and this shouldn't happen anymore
