### ISSUE TITLE
Playing tab show Album Artist instrad of Artist tag

### ISSUE THREAD

**Issue by Monirzadeh** [UnicornsOnLSD/finamp#193]
when you play music it show Album Artist below the cover instead of show Artist tag
if you open album from `Artist A` than in Album one track has `Artist B` show wrongly `Artist A` name in playing name.

**Comment by UnicornsOnLSD** [comment]
Do you mean the sort of thing that was fixed in #116?

**Comment by Monirzadeh** [comment]
> as fix

i use last version on fdroid but it is not show the correct name
![photo_2022-02-21_19-36-22](https://user-images.githubusercontent.com/25131576/154990996-b7e89f15-61f7-422e-8051-77b1868304a6.jpg)
this file has this tag
Album Artist :Daniel Hart
Artist: Daniel Hart; Dark Rooms
it should show 
Daniel Hart; Dark Rooms

**Comment by Maxplosion** [comment]
@Monirzadeh - as far as I remember there was no release yet with PR #116 in it, so you'll have to wait for a new release.

**Comment by UnicornsOnLSD** [comment]
> @Monirzadeh - as far as I remember there was no release yet with PR #116 in it, so you'll have to wait for a new release.

This is correct, closing since the issue has already been fixed
