### ISSUE TITLE
SD Card storage

### ISSUE THREAD

**Issue by jugendhacker** [UnicornsOnLSD/finamp#20]
Hi,

I just stumbled upon this app, which seems the only jellyfin app that has download support. As I store my music as FLAC it would be really nice if I could select SD-Card as storage, to not fill up my internal storage.

**Comment by UnicornsOnLSD** [comment]
Configurable storage locations are a planned feature and shouldn't be too hard to do.

**Comment by Joshfindit** [comment]
I would also like to suggest “Files” storage on iOS so that downloaded files are deleteable  and playable in other apps.

**Comment by UnicornsOnLSD** [comment]
Downloaded songs aren't named in a human-readable format (unless you know the Jellyfin item IDs of all of your songs). Also, deleting a song is more complex than just deleting the file. The item's metadata also has to be deleted from the database, and the file has to be deleted using the downloads system for the "downloaded items" count to go down. When I add it, I'll have to put a warning somewhere telling people not to delete files from the custom directory directly.

**Comment by Joshfindit** [comment]
If I were building this for myself, I would store the human-readable filename with a metadata filename next to it

```
artist - song.flac
artist - song.meta
```
(where meta is whatever filetype is the fastest)
meta would then hold the original metadata (including item ID) as well as any additional app-specific metadata such as playcount or last sync time.
In my experience local storage volumes are fast enough to make this kind of thing performant for even thousands of items, but if not I would store an index and rebuild it as a background task (and expose the rebuild as a button for the user).

I don't know if that's interesting or in line with the goals of this project, but it's the kind of control *I*'ve been looking for in a sync-able music client.

**Comment by jugendhacker** [comment]
@Joshfindit maybe better open another issue about saving the music on storage that every app could read. Because the intention behind my issue is something else than you wan't, I just wan't an option to store the downloads in the apps "private" storage on the SD card.

**Comment by UnicornsOnLSD** [comment]
@Joshfindit I definitely see where you're coming from, but storing metadata in text files makes development much harder. Firstly, I'd have to serialise/deserialise metadata, which would add a performance overhead. It would also be harder to query and loop through downloaded songs. Storing songs by their item IDs makes it easier to load songs too. The database that I'm using (Hive) also allows for synchronous access to the database (Hive keeps everything in memory while running), which makes working with downloaded songs way easier.

**Comment by Joshfindit** [comment]
> @Joshfindit maybe better open another issue about saving the music on storage that every app could read. Because the intention behind my issue is something else than you wan't, I just wan't an option to store the downloads in the apps "private" storage on the SD card.

You're totally right and I apologize. My intent was simply to say "If you build configurable storage locations, consider building it with serialize/de-serialize as well", but it got out of hand.

**Comment by UnicornsOnLSD** [comment]
@Joshfindit I've just thought about a way that I could store downloaded songs in a human-readable format. Currently, the app is hard coded to get songs by going to the app directory and loading the file with the song's ID (and the file extension, which is stored separately). To do custom storage paths, I'd have to store the song's path anyway. With this, I could make it so that downloads are stored with human-readable names instead of IDs.

As for metadata, I could have a settings option to dump metadata to .JSON files (or another format, if there's something more suitable).

**Comment by UnicornsOnLSD** [comment]
This has been implemented and will be in 0.4.0. There's a new settings menu screen for adding custom storage locations. Songs are stored as {artist}/{album} - {song}.{extension}, so you should be able to fall back on another media player if you want. This also works on SD cards on Android. As for iOS Files (#25), I still need to add the storage permission stuff for iOS, but after that it should work.

**Comment by Joshfindit** [comment]
That’s amazing. Thank you, and 🙌

**Comment by seniorm0ment** [comment]
Is this still in the app? I do not see an area to add custom storage locations (or add/remove the ones it's grabbing from jellyfin either)

**Comment by UnicornsOnLSD** [comment]
Storage locations can be added by going to settings > download locations

**Comment by seniorm0ment** [comment]
Oh that seemed like it was for where to download songs for offline, not local storage playback.
Unless I'm misunderstanding

**Comment by UnicornsOnLSD** [comment]
Oh yeah, Finamp can't play back songs from storage unless they've been downloaded through Jellyfin. I don't really have any plans to add this since Finamp is meant to solely be a Jellyfin client and not a general music client.

**Comment by seniorm0ment** [comment]
Ah ok :/
Thanks
