### ISSUE TITLE
NoSuchMethod Error

### ISSUE THREAD

**Issue by nathancoooper** [UnicornsOnLSD/finamp#206]
When I open the Finamp app I receive this:
![image](https://user-images.githubusercontent.com/100081814/161380836-c5a01748-a423-4662-af12-8ceb0df65d43.png)

The logs state:
![image](https://user-images.githubusercontent.com/100081814/161380841-b4dcd068-39ee-49a1-86f8-502c298b834f.png)

**Comment by nathancoooper** [comment]
(platform: iOS 15.0.2 - iPhone SE Gen. 2)

**Comment by UnicornsOnLSD** [comment]
Duplicate of #72
