### ISSUE TITLE
Unable to swipe away paused playback

### ISSUE THREAD

**Issue by jugendhacker** [UnicornsOnLSD/finamp#21]
If I play music, then pause it, the media notification cloud not be swiped away like with other music apps. I'm only able to remove it, by closing the app from the app drawer.

**Comment by UnicornsOnLSD** [comment]
What Android version are you on?

**Comment by jugendhacker** [comment]
I'm on Android 9 (Samsung Stock ROM, so One UI 1.1)

**Comment by UnicornsOnLSD** [comment]
The new release changed some stuff related to how the audio service acts when paused. Could you try this again?

**Comment by jugendhacker** [comment]
Yeah I'm now abled to swipe away the paused playback as expected.
