### ISSUE TITLE
[Bug] ALAC files don't stream directly (iOS 0.6.1)

### ISSUE THREAD

**Issue by TinDefacto** [UnicornsOnLSD/finamp#225]
Hi there!

First off, LOVE the app, and it's made listening to music such a better experience when away from home. Thank you!!

I just found out the app had been updated and was elated to find so many of the changes I'd been looking for. Alas, for some reason, the update seems to have caused a new issue: any ALAC files on my Jellyfin server will not play directly. They'll work if transcoded, and any file that isn't ALAC works perfectly fine without transcoding. But since 97% of my library is in ALAC, and I'd prefer to stream directly, this is a bit of an issue!

My apologies if this has been covered elsewhere. I'm not sure what could have changed about the update to disturb this playback, but I hope it's not too difficult to fix!

Thanks again!

**Comment by UnicornsOnLSD** [comment]
This may be an issue with the audio plugin I'm using, I'll see if I can find where ALAC broke since I'm pretty sure it worked in the last release

**Comment by TinDefacto** [comment]
Yes, ALAC definitely worked fine before I updated! (Though I did skip 0.6.0.)

**Comment by UnicornsOnLSD** [comment]
Found the bug, it's here: https://github.com/UnicornsOnLSD/finamp/blob/master/lib/services/MusicPlayerBackgroundTask.dart#L541

Safari includes `m4a|alac` in its `Container` parameter, I'll clean this up to properly select the codec for each platform.

**Comment by UnicornsOnLSD** [comment]
Sort of fixed in 40d9a6d by adding `m4a|alac` to the supported containers, I'll fix this up properly at some point (i.e. actually checking the supported codecs on-device)

**Comment by csaavedra** [comment]
Sorry to relive this, but I noticed today that ALAC is not playing when streaming. I have the latest Android release from the Google Play store. Is the bug fix above already released?

**Comment by jmshrv** [comment]
ALAC isn't supported in ExoPlayer, so it can't work in the current system. When I get around to #177, it'll work, but that's ages away. If I were you I'd consider converting your music to FLAC if possible, but I understand that doing that is really inconvenient (especially if you value the idea of keeping the exact files over the decades).

**Comment by csaavedra** [comment]
No worries. It's a lossless format so converting to FLAC shouldn't change anything.
