### ISSUE TITLE
Music now only appears in the "Genres" category

### ISSUE THREAD

**Issue by andrewspiers** [UnicornsOnLSD/finamp#228]
Hi, I was exploring the different sort options for albums, and now the albums, artists, playlists, and songs categories all say 'No items found' no matter what I sort by. It is still there under "Genres" though.

Running on Finamp 0.6.1 on a Pixel 6.

**Comment by UnicornsOnLSD** [comment]
You probably pressed the favourites button. I should probably figure out a better UI for that, there have been a few people who've asked where their music has gone when they've just had that filter on
