### ISSUE TITLE
[Feature Request] ogg implementation for IOS

### ISSUE THREAD

**Issue by proline** [UnicornsOnLSD/finamp#236]
Hello, 
I have a lot of my music file in ogg. But on IOS it is impossible to read it.
Is it possible to implement natively this format on the app ?

**Comment by UnicornsOnLSD** [comment]
This is not possible due, it's up to Apple to add OGG support to iOS's media player. There have been a few issues about this, but the one with the most discussion is at #177.

**Comment by proline** [comment]
One question in that case how spotify, that uses OGG can work on IOS?

**Comment by UnicornsOnLSD** [comment]
I can't give a definitive answer to that as Spotify is closed source, but in their third-party licenses they list libogg, libvorbis and flac. My guess would be that they're encoding the music to a compatible format as it comes in, or they've developed something entirely custom for playing music. As for VLC, that plays music via libvlc, which does support OGG. Finamp just uses Apple's built-in players, as said in #177. I'm going to experiment with other backends at some point - I was considering a GStreamer based implementation, but I want to see if I can get [just_audio_mpv](https://github.com/bleonard252/just_audio_mpv) working on Android/iOS, assuming there aren't any legal issues there.
