### ISSUE TITLE
Issue with sleep timer

### ISSUE THREAD

**Issue by Demian98** [UnicornsOnLSD/finamp#241]
I'm using the sleep timer a lot and it is a great feature. But when the sleep timer is stopping the playback, it is not just pausing the playback, it is jumping to the first track of the album.
It would be great if the sleep timer could just pause the playback, without reseting the current track. So at the morning I can continue listening where it stopped in the night.

Thank you for creating such a beautiful app :)

**Comment by UnicornsOnLSD** [comment]
Changed in de06e341ae8dc597513450fb4e656f688c64fb26 :)

**Comment by Demian98** [comment]
Thank you very much for the quick fix :)
