### ISSUE TITLE
Weird screen/GPU artifacts on Android app

### ISSUE THREAD

**Issue by usergitty** [UnicornsOnLSD/finamp#244]
Hi,
I just found out about Finamp and it looks amazing, I really want to use it but as soon as i installed it, I got these weird artifacts and the whole GUI goes crazy. I've never seen anything like this with any other app. 

I'm running LineageOS 18.1 on OnePlus One. Got the latest version of the app from Fdroid.

![ezgif-3-a5dd0bb058](https://user-images.githubusercontent.com/106674296/171405541-5eb65b8c-e06c-43b3-b1ac-0300b7cd1024.gif)

**Comment by usergitty** [comment]
> That's interesting. Does this happen after a reboot?

Yes. and I've also tried reinstalling the app directly using the .apk file. Still goes crazy.

**Comment by usergitty** [comment]
Yup, I get the same thing with Flutter Gallery.
Did a quick search and found this old post.

https://github.com/flutter/flutter/issues/13589

**Comment by UnicornsOnLSD** [comment]
Looks like this is an issue with Flutter itself then. I couldn't find any specific report on the OnePlus One, so it may be worth reporting.

**Comment by UnicornsOnLSD** [comment]
Closing as this seems to be a Flutter issue

**Comment by dogtopus** [comment]
Might be a bug with older Adreno GPU drivers. Similar glitches (but not occurring at the exact place) can be seen on my Adreno 420 on a Nexus 6.
