### ISSUE TITLE
Feature request: User-manageable “Files” storage on iOS

### ISSUE THREAD

**Issue by Joshfindit** [UnicornsOnLSD/finamp#25]
As mentioned in https://github.com/UnicornsOnLSD/finamp/issues/20.

Based on the the items mentioned:
> Firstly, I'd have to serialise/deserialise metadata, which would add a performance overhead. It would also be harder to query and loop through downloaded songs. Storing songs by their item IDs makes it easier to load songs too. The database that I'm using (Hive) also allows for synchronous access to the database (Hive keeps everything in memory while running), which makes working with downloaded songs way easier.

I no longer think this feature request is reasonable for finamp, but it now has it's own issue that can be commented on separate from the request for SD Card storage.

**Comment by UnicornsOnLSD** [comment]
Added :)
