### ISSUE TITLE
Repeat single Track functionality

### ISSUE THREAD

**Issue by Maxplosion** [UnicornsOnLSD/finamp#26]
Hi, 
first of all great app, love the offline feature!
Would it be possible to add "repeat 1" in one of the next releases?
I sometimes like to listen to one song on repeat and currently only "repeat all" or "repeat none" is possible as far as I could see. 
br

**Comment by UnicornsOnLSD** [comment]
That would be easy to add, I'll add it in the next release.

**Comment by UnicornsOnLSD** [comment]
Added :)
