### ISSUE TITLE
[Feature Request] Show quality of current song playing / songs in library

### ISSUE THREAD

**Issue by GreenCobalt** [UnicornsOnLSD/finamp#260]
Similar to Plexamp's version of this - just show like "MP3 320kbps" or "FLAC 44.1/24". 
Shown under the Now Playing screen, maybe where it says "Streaming \n Direct", change it to "Direct \n *quality*"?

Also at the bottom of albums it'd be nice to have just a little badge showing this.

**Comment by UnicornsOnLSD** [comment]
Duplicate of #211
