### ISSUE TITLE
Feature Request: Show Track Artist next to Play Time in Album View

### ISSUE THREAD

**Issue by k1llerk3ks** [UnicornsOnLSD/finamp#265]
Artists might be different from the Album Artist printed at the top. I request adding this information to the album-view screen, my recommendation for the location is next to the Play Time.

A general Idea would be to add developer settings, where you can turn on/off such behavior

![Screenshot_20220707-153149_Finamp](https://user-images.githubusercontent.com/97703119/177786667-a750f418-e5eb-45ce-a736-5bbe49781cea.png)

(Thumbs up to Finamp! It gets better with every release! <3 )

**Comment by TinDefacto** [comment]
I like that idea! And if I may add a further suggestion, it'd be great if the track artist appeared there only if the album is mixed. :) (i.e. if it's just a Nine Inch Nails album, I wouldn't want to see "Nine Inch Nails" there for each track.)

**Comment by rom4nik** [comment]
1|2
---|---
![Screenshot_20220713-214338_Finamp](https://user-images.githubusercontent.com/46846000/178818884-e8a48278-06dc-45d5-8669-7f7c34b1f23a.png)|![Screenshot_20220713-214106_Finamp](https://user-images.githubusercontent.com/46846000/178818911-fa6bb795-cbcb-42e9-ae88-515a3a4c6e18.png)

Which design do you like better? I think the second looks less cluttered, and would let keep the artists text even if they're the same as album artists (just like web client does it). @UnicornsOnLSD

**Comment by UnicornsOnLSD** [comment]
I think 1 could look the best if we add a separator (maybe something like a dash or the · character), also the play time should be the subtitle colour instead of the title colour. 2 and 3 also look good, but I'm not a fan on how the download indicator is positioned. Maybe if it was put with the subtitle like how Spotify does it?

![49917864-C09B-48EA-95A1-FDCB29F23831_1_201_a](https://user-images.githubusercontent.com/44349936/179098518-906269ee-357a-4e63-b0d8-0ce9f02d47cd.jpeg)

**Comment by rom4nik** [comment]
Added favorited icons, artists detection is also fixed now.
![Screenshot_20220720-235903_Finamp](https://user-images.githubusercontent.com/46846000/180090111-3b160189-bbfa-44b9-af3a-f9257bb10f15.png)

**Comment by UnicornsOnLSD** [comment]
That looks great! I agree that a heart makes more sense. If you're not already, have you tried using a WidgetSpan for the download indicator? That might properly constrain the download icon to the text size. https://api.flutter.dev/flutter/widgets/WidgetSpan-class.html

**Comment by rom4nik** [comment]
Best I could achieve was applying Offset(-3, 0) to the indicator widget. Looks almost perfectly in line with track number, and apparently doesn't break on different DPIs I've tested. I'll get the settings option working and submit a PR.

![Screenshot_20220723-014508_Finamp](https://user-images.githubusercontent.com/46846000/180581219-f47d7133-d4ad-41af-87e5-6de99ba9583e.png)
