### ISSUE TITLE
Error 301 when connecting

### ISSUE THREAD

**Issue by hydrx** [UnicornsOnLSD/finamp#275]
I'm getting an Error 301 when trying to connect to my server using the public domain name that's set up through Cloudflare tunnel.
I am able to connect while on my local network using the local IP and port, though.

Using the Jellyfin app allows me to connect with the public domain name, so I know it works, but Finamp throws an error.

**Comment by hydrx** [comment]
I apologise, it was due to user error

**Comment by lmacknicki** [comment]
I am having this same problem with the same setup through a cloudflare tunnel.  What was your user error?

I can connect through the tunnel just fine through a browser and through the JellyFin iOS app.
