### ISSUE TITLE
Feature Request : Add a "Play Next" button after a long press on a song

### ISSUE THREAD

**Issue by Fabien98** [UnicornsOnLSD/finamp#277]
First, Thanks for the very good App!
I would like to have the ability to play a song just next to the one which is currently playing.
When you use the "Add to current playlist" button it adds the song at the very end of the playlist.
This feature exists in the jellyfin official App.

I hope it's clear

**Comment by Fabien98** [comment]
Ok thanks for the reply.
I tried to search if my suggestion existed before posting but didn't find the #92 feature request.. sorry!
If you consider it's a duplicate you can close this issue!

**Comment by UnicornsOnLSD** [comment]
Closed as duplicate (thanks for pointing it out @rom4nik !)
