### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by RJswap** [UnicornsOnLSD/finamp#28]
I can access my jellyfin server remotely using firefox (https://mydomain.org). The certificat is generated by ovh using a free certificat service. But I can't log in with Finamp I have this warning message :

[]()![Screenshot_2021-04-30-12-34-01-219_com.unicornsonlsd.finamp.jpg](https://user-images.githubusercontent.com/61156795/116683834-6f34c680-a9b0-11eb-8b12-e63a148804e0.jpg)

**Comment by UnicornsOnLSD** [comment]
Are you using a self-signed certificate?

**Comment by RJswap** [comment]
Thank you for the reply ! It looks like my certificate is not applied to my subdomain. I believe that is the problem I will investigate on this side.
