### ISSUE TITLE
[Feature Request] Click on Artist Name from Album View

### ISSUE THREAD

**Issue by TinDefacto** [UnicornsOnLSD/finamp#280]
Hi!

I often find myself trying to click on the artist name when viewing an album to try to view all albums by that artist.

For instance, if I'm looking at the album page for Depeche Mode's "Construction Time Again" (i.e. the list of tracks), it lists the basic info of the album at the top (artwork, artist, year, length). It'd be super helpful to be able to click on the artist name and see all of Depeche Mode's albums instead of having to exit that view, go to artists, find Depeche Mode and click on them from there.

I hope that explanation makes sense! My apologies if this has already been a requested feature; I wasn't able to find it if so.

Thanks again!!

**Comment by TinDefacto** [comment]
Ohhh I'm dumb and hadn't seen that there was an update last week that did exactly this. Thank you. :D

**Comment by UnicornsOnLSD** [comment]
No worries, it's only just got approved recently so it's not like you've had long to see :)
