### ISSUE TITLE
Download counter not visible when using light theme

### ISSUE THREAD

**Issue by asgardius** [UnicornsOnLSD/finamp#285]
When using Finamp with new light theme download counter at top left is not visible due text color is same as background. Changing color from white to grey is visible on both themes. Here is the result
Before
![Screenshot_20220722-133501_Finamp](https://user-images.githubusercontent.com/43385234/180566063-f32d21f2-eeab-4111-b8a6-818ab833a756.png)
After
![Screenshot_20220722-133755_Finamp](https://user-images.githubusercontent.com/43385234/180566101-d9a59484-3807-4d50-9a3d-b008686ff118.png)

If this is a good idea i can make a pull request

**Comment by UnicornsOnLSD** [comment]
Thanks for pointing this out, it would be great if you made a PR for this :)
