### ISSUE TITLE
[Bug/Issue] Selecting grid will never show the album art

### ISSUE THREAD

**Issue by florinsdistortedvision** [UnicornsOnLSD/finamp#299]
As the title implies, selecting grid will forever make the album art never load and show the blank CD icon. Switching back to list will fix it.

![image](https://user-images.githubusercontent.com/97384306/183754150-4a65bbc2-0c0e-4861-98d4-f0e464bf5ccf.png)

![image](https://user-images.githubusercontent.com/97384306/183754160-4dbe9a73-6299-4029-9a13-150779c4c5e3.png)

**Comment by UnicornsOnLSD** [comment]
I can't reproduce this. Could you send logs?

**Comment by florinsdistortedvision** [comment]
> I can't reproduce this. Could you send logs?

Never mind, my server had issues, closed it as fast as I could after confirming it
