### ISSUE TITLE
[Feature Request] Music genre, shuffle all

### ISSUE THREAD

**Issue by MegaS0ra** [UnicornsOnLSD/finamp#30]
I've just discovered this app and it's great!
Helps a lot as the Jellyfin app stutters when playing music in background. 

Personally, I think these features could be nice, as I'm used to use it in other music apps :
- Ability to browse music by genre ;
- Ability to shuffle all songs in the library ;
- Ability to shuffle all songs of an artist/of a music genre ;

Or maybe some of this can be achieved by creating playlists?

Thank you 😊

**Comment by UnicornsOnLSD** [comment]
Next release will likely focus on this stuff, since all of those are heavily requested features

**Comment by josephsmendoza** [comment]
+1 for browsing my genre. In multi user systems like mine this is the feature we use in Gelli to only hear our own music in a shared library.

**Comment by UnicornsOnLSD** [comment]
Genres added in 09e91a8d86793ec8854015ab4d20471f70586ab9

**Comment by UnicornsOnLSD** [comment]
Shuffle all added in 1c16f10
