### ISSUE TITLE
Queue Management

### ISSUE THREAD

**Issue by Maxplosion** [UnicornsOnLSD/finamp#33]
Hi, 
quick question, is there a way to manage the current queue of tracks that are played? 
E.g. removing a track or adding new tracks to the queue? Have tried long presses, swipes and so on. 
If not, do you plan on adding this, as its the one thing that is currently missing for me to make it my daily driver.
Br

**Comment by UnicornsOnLSD** [comment]
You can swipe away songs in the current queue by opening the queue on the player screen (little icon in the bottom right) and swiping them away. As for adding stuff to the queue, it's planned.

**Comment by Maxplosion** [comment]
Perfect, thanks for the info and looking forward to the 'add to queue' feature'
