### ISSUE TITLE
Could not donwload on to SD-Card

### ISSUE THREAD

**Issue by jugendhacker** [UnicornsOnLSD/finamp#37]
When I try to download to a folder on the SD-Card it says "downloads added" but shortly after it shows "an error occurred". If I click on more nothing happens, no further details about the error are shown. The music does not get downloaded.

I'm on Samsung Stock ROM running Android 9 (OneUI 1.1)

**Comment by UnicornsOnLSD** [comment]
Can you send your logs from the logs screen? There's a copy button in the
top right

**Comment by jugendhacker** [comment]
Looks like android permission system forbids to save it in this folder.

```
[DownloadsHelper/SEVERE] 2021-05-12 13:51:50.886467: FileSystemException: Creation failed, path = '/storage/E058-1CEE/Musik/twenty one pilots' (OS Error: Permission denied, errno = 13)
```

**Comment by UnicornsOnLSD** [comment]
In that case, you should use the app directory option when adding a custom location. It will still write to external storage, it would just be in the app's own directory instead of a custom one. As far as I know, this is a Flutter limitation since it doesn't support scoped storage.

**Comment by jugendhacker** [comment]
This works, thanks
