### ISSUE TITLE
[Feature Request] Support for FLAC playback

### ISSUE THREAD

**Issue by silentsilas** [UnicornsOnLSD/finamp#39]
I noticed some of my albums weren't playing on iOS. Discovered they were all FLAC files. It seems like audio_service allows you to use different audio plugins, but I have no idea if there's one that works with FLAC.

Alternatively, a good workaround would be transcoding, which I see is a planned feature 👍

**Comment by UnicornsOnLSD** [comment]
FLAC should work on iOS (or at least it did when I tested it). Transcoding is supported and can be enabled in the settings.

**Comment by silentsilas** [comment]
Welp, you're right. I ran another release build and could download the FLAC album and play it offline without issues. Sorry about this!
