### ISSUE TITLE
[Feature Request] Skip library selection when there's only one choice

### ISSUE THREAD

**Issue by sugoidogo** [UnicornsOnLSD/finamp#42]

**Comment by UnicornsOnLSD** [comment]
You only have to input a library once, so I don't think that it's worth bothering with auto-selection. I'd also assume that most people have multiple libraries.

**Comment by josephsmendoza** [comment]
well there's no need to assume, you could leave the issue open as last priority and possibly bump it up if more people show support for it.

**Comment by UnicornsOnLSD** [comment]
Good point. I'll keep it reopen, and might implement it in the next update.
