### ISSUE TITLE
[Feature Request] Sorting by...

### ISSUE THREAD

**Issue by bobberb** [UnicornsOnLSD/finamp#46]
Jellyfin allows sorting albums/artists by recently added, alphabet, etc. Finamp should do the same.

**Comment by UnicornsOnLSD** [comment]
I was going to add this before release (#9), but probably got lazy and thought I'd do it later. I've got a lot planned for this release, but I should be able to fit this in.

**Comment by UnicornsOnLSD** [comment]
Added in f5e4a4f
