### ISSUE TITLE
Songs with a slash in the title error when downloading

### ISSUE THREAD

**Issue by lazybookwyrm** [UnicornsOnLSD/finamp#49]
Went to download my Celtic Woman album and "Last Rose of Summer (Intro) / Walking in the Air" and "The Ashoken Farewell / The Contradiction" both had download errors. I'm guessing the file name is being pulled from the song's title and that's what's causing the error.

**Comment by UnicornsOnLSD** [comment]
Can I see your logs? Downloads are done by item ID, so that shouldn't be the issue. It could be messing something up elsewhere though.

**Comment by lazybookwyrm** [comment]
[Error Log.txt](https://github.com/UnicornsOnLSD/finamp/files/6557218/Error.Log.txt)

**Comment by UnicornsOnLSD** [comment]
Try redownloading them before sending logs. Logs aren't saved between sessions.

**Comment by lazybookwyrm** [comment]
This should be the relevant log. Closed the app, tried downloading, then copied the logs [Error.Log.txt](https://github.com/UnicornsOnLSD/finamp/files/6557240/Error.Log.txt)

**Comment by lazybookwyrm** [comment]
Just noticed a couple albums weren't downloading at all and all of their album titles had colons in them, guessing it's something related.

**Comment by UnicornsOnLSD** [comment]
I'm assuming you're downloading to a custom location. If you are, try these APKs (built from 477b006), which replace "/" with "_" and ":" with "__". I'll improve the substitutions later but this is just for testing at the moment.



[app-arm64-v8a-release.zip](https://github.com/UnicornsOnLSD/finamp/files/6557303/app-arm64-v8a-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/UnicornsOnLSD/finamp/files/6557307/app-armeabi-v7a-release.zip)
[app-x86_64-release.zip](https://github.com/UnicornsOnLSD/finamp/files/6557310/app-x86_64-release.zip)

**Comment by lazybookwyrm** [comment]
That works, thanks! And thanks for your work on the app

**Comment by UnicornsOnLSD** [comment]
I added a proper fix in the big null safety commit. The characters / ? < > \ : * | " will all be replaced with an underscore.
