### ISSUE TITLE
Made a logo for Finamp.

### ISSUE THREAD

**Issue by GildartsClive** [UnicornsOnLSD/finamp#52]
Made a logo for Finamp here are the vector and a png file. I used Inkscape to make it.

[png file](https://www.dropbox.com/s/cyo3rk8fcgg66fp/Finamp.png?dl=0)
[svg file](https://www.dropbox.com/s/l47uemrkss494l0/finampLogo.svg?dl=0)

**Comment by UnicornsOnLSD** [comment]
Looks great, thanks! I'll add it in the next release :)

**Comment by UnicornsOnLSD** [comment]
Added in 723eb59a1ebc3b5bb454024b4c19552153721eb2

**Comment by UnicornsOnLSD** [comment]
Hey, could I have the Inkscape file? I'm adding it to the Jellyfin Clients page, and it'd be more efficient to have an optimised SVG output (https://github.com/jellyfin/jellyfin-blog/pull/96)

**Comment by GildartsClive** [comment]
the svg file is in the first post of this thread

**Comment by UnicornsOnLSD** [comment]
Thanks, didn't realise that Inkscape just saves its files as SVG
