### ISSUE TITLE
Search by song title

### ISSUE THREAD

**Issue by kernitus** [UnicornsOnLSD/finamp#53]
Hello, thanks again for the great work.

I have a simple feature request - to be able to search by song title rather than having to search the artist, select an album and then the song. Ideally by having a tab called "songs" where you can scroll and search through all the songs. There doesn't see to be an issue open for this already, although it is a similar concept to #30, except for songs, not genres.

**Comment by UnicornsOnLSD** [comment]
Once I implement #30, this should "just work". Searching will search in the current category, so searching in the songs tab will search only for songs.

**Comment by UnicornsOnLSD** [comment]
Added the songs tab in fe0941f432feb01c673fe6eaded4258699b13d0c, so search works too.
