### ISSUE TITLE
iPad lacks access to media controls in landscape.

### ISSUE THREAD

**Issue by Bitwolfies** [UnicornsOnLSD/finamp#63]
Just blows up the album art, no controls available 
![AE0C876B-D14B-4E6A-91A4-E75129004AF9](https://user-images.githubusercontent.com/65789901/125227574-fabbb500-e287-11eb-8c3d-bc0704ae58b0.png)

**Comment by UnicornsOnLSD** [comment]
This also happens when you turn a phone landscape, should be an easy fix.

**Comment by UnicornsOnLSD** [comment]
Fixed in 31cccca24127f0327c6bb0bd9f0d2839505b5381 and 767d31bd88fc43e253ee2ceb04aeb79cf52aa0be
