### ISSUE TITLE
Pre-select the last used storage option in a "Download" dialog dropdown.

### ISSUE THREAD

**Issue by Liarra** [UnicornsOnLSD/finamp#65]
Hi there,
Great app! Thank you so much, I'm super happy to be able to download my Jellyfin music at long last :smile: 
I'm probably going to be spamming here with some usability issues / bugs I find.

Here is one:
When downloading an album, I am faced with a drop-down field where nothing is initially selected. I have to select the download location every time, even though I only really have one option. I guess most Android users prefer to store all their music in one place as well.

It would be good if the app could remember the last selected option and pre-fill it for all new Download dialogs. And if there is only one option available (which is true for all iOS devices I think), this option could be pre-selected by default even for the first ever Download.

**Comment by UnicornsOnLSD** [comment]
That's a good idea, I should be able to do that pretty easily :)

**Comment by UnicornsOnLSD** [comment]
Also, you can still set a custom directory in your phone's storage on iOS, so iOS users can still have multiple directories.

**Comment by bambadon** [comment]
I would prefer never having the prompt show up (iOS). If there still is a reason to maintain this selection screen on iOS, maybe allow for a setting to disable this prompt. My hunch is that most users would never need it. Apps like Spotify allow the user to just tap the download icon, which is very user friendly.

**Comment by Liarra** [comment]
It could be a setting (in "Settings" view, naturally) that the user needs to set once and for all.

I think Android users would be happier if allowed to pick between internal and external storage; I heard one complain about this exact issue when talking about Spotify app.

**Comment by drazil100** [comment]
The way it works currently is you need to go into Settings > Download Locations if you want to add alternative download locations. What I might suggest is not only make it so the last selected download location is pre-selected but that it doesn't even give a prompt if you don't have any manually added alternative download locations.

**Comment by UnicornsOnLSD** [comment]
There will no longer be a prompt if there is only one download location (6ed90fd). Considering it closed since people with multiple locations would probably want to select one each time.
