### ISSUE TITLE
Audio Service logs showing blank screen

### ISSUE THREAD

**Issue by Norakthes** [UnicornsOnLSD/finamp#66]
I went to look at the Audio Service logs on my Nubia Z20 (NX627J) running Android 9, and when I looked at them, all I could see was a blank screen, and the copy all button in the top didn't seem to do anything. 
I tried to look at the logs because I was troubleshooting a problem with a handful of FLACs not playing nice with direct play, but it seems I have to wait to look into that. 
![Screenshot_20210712-152932.png](https://user-images.githubusercontent.com/30022536/125296602-bf23f800-e326-11eb-9fff-44d6dc66700e.png)

**Comment by UnicornsOnLSD** [comment]
Fixed in 22ba663. Just wondering, what issues were you having with FLAC playback?

**Comment by Norakthes** [comment]
Ok, thanks 👍

**Comment by Norakthes** [comment]
> Fixed in 22ba663. Just wondering, what issues were you having with FLAC playback?

Some songs would play, but no audio would come out. The issue was only with a few specific ones
