### ISSUE TITLE
[Feature Request] Show Embedded Art in mp3

### ISSUE THREAD

**Issue by cfredericksen** [UnicornsOnLSD/finamp#69]
Jellyfin web/native IOS app has this ability to show the embedded artwork in the mp3 if the folder.jpg doesn't exist in the folder. It would be great if Finamp could too.

**Comment by UnicornsOnLSD** [comment]
Finamp uses the item's parent (usually an album) to get album art. It'd be kind of clunky to have to fall back on to song art since then each piece of album art would make two network requests. If I were you, I'd just organise your library to include folder.jpgs.

**Comment by cfredericksen** [comment]
I have a 'new music' folder, contains mp3s of different artists/songs and sorted by newest created date in Finamp(thanks for adding the sort!). Then if I keep a song, I run it through beets and added to my main Music folder and in its proper Album folder. I guess that's the 'why' I am requesting it.

**Comment by SebyakinAndrei** [comment]
For me, cover arts don't work too. As I understand, right not finamp can only work with folder album structure, getting preview from cover.jpg. But my music is poorly structured, and have a lot of music from one genre in one directory. And I think most people have similar setup. But official app is completely fine with it. I'll attach two screenshots, for better visualization of a problem.
Official app:
![image](https://user-images.githubusercontent.com/12896581/129182169-81aeb0d0-6d03-405c-9dad-963c61149c98.png)

Finamp:
![image](https://user-images.githubusercontent.com/12896581/129182202-d897f08b-7d6b-4354-8cc1-5af460267894.png)

I really like the native look-and-feel of Finamp, so it would be great if can be completed with working cover arts :)

**Comment by manjotsc** [comment]
Same here

**Comment by UnicornsOnLSD** [comment]
@SebyakinAndrei @manjotsc I've just pushed some commits that should fix this (if an item has its own image it will be used instead of the parent image). I've attached the APK below if you'd like to try it out, but some stuff may be jank (although I can't really think of any new bugs right now) and you can't downgrade without wiping your app data, so be careful :)

[app-arm64-v8a-release.zip](https://github.com/UnicornsOnLSD/finamp/files/7146635/app-arm64-v8a-release.zip)

**Comment by manjotsc** [comment]
@UnicornsOnLSD Thanks, It's working fine.

![Screenshot_20210911-060038](https://user-images.githubusercontent.com/51430971/132944162-242d6123-3977-494c-94c4-32431af990b6.jpg)
![Screenshot_20210911-060028](https://user-images.githubusercontent.com/51430971/132944164-43e90a40-0f12-4140-a6e8-3885231dbde5.jpg)

**Comment by manjotsc** [comment]
@UnicornsOnLSD one bug maybe, when I turn on the offline mode. All songs art disappears and appears again when offline mode is off.

**Comment by UnicornsOnLSD** [comment]
@manjotsc Album art isn't saved in offline mode yet, I'm going to work on that next. For now, disabling album art in offline mode is what its meant to do.

**Comment by manjotsc** [comment]
@UnicornsOnLSD Alright, I'll wait for update.

**Comment by cfredericksen** [comment]
> @cfredericksen @SebyakinAndrei @manjotsc I've just pushed some commits that should fix this (if an item has its own image it will be used instead of the parent image). I've attached the APK below if you'd like to try it out, but some stuff may be jank (although I can't really think of any new bugs right now) and you can't downgrade without wiping your app data, so be careful :)
> 
> [app-arm64-v8a-release.zip](https://github.com/UnicornsOnLSD/finamp/files/7146635/app-arm64-v8a-release.zip)

Shucks, I'm on IOS but thanks for the commits!

**Comment by manjotsc** [comment]
@cfredericksen Was art album fixed in this update, because art still not working in Offline Download.

**Comment by cfredericksen** [comment]
> @cfredericksen Was art album fixed in this update, because art still not working in Offline Mode.

@manjotsc I dont know. I am not on Android and he posted a APK to test.

**Comment by UnicornsOnLSD** [comment]
I'm considering this fixed since @manjotsc showed it working fine.
