### ISSUE TITLE
Feature Request - V9.5 Beta - allow to filter favorite songs in offline mode

### ISSUE THREAD

**Issue by enduring78** [UnicornsOnLSD/finamp#702]
Filtering in the song list based on favorite/liked songs is only possible in online mode. Is would be great if this would be possible as well in offline mode, or create a dynamic playlist that lists all favorite songs.

**Comment by Chaphasilor** [comment]
FYI you can edit both comments/issues and issue titles on GitHub, so there's no need to create a new issue next time ^^
