### ISSUE TITLE
[Bug]: Deselecting a music library has no effect

### ISSUE THREAD

**Issue by MattBlackOnly** [UnicornsOnLSD/finamp#784]
I have multiple music libraries, but I cant deselect any from the "Select Music Libraries" settings page. As it just reverts back to selecting all.

1. Open settings
2. Hit select music libraries
3. Deselect a library
4. Hit the tick button on the bottom right (accept?)
5. Go back in and they are all selected again...

Any ideas?

**Comment by Chaphasilor** [comment]
Is that on the stable version or beta version?  
For me it works as expected on the latest beta (0.9.8)...

**Comment by MattBlackOnly** [comment]
> Is that on the stable version or beta version? For me it works as expected on the latest beta (0.9.8)...

It's 0.6.23 on Android.
And using Jellyfin 10.9.6 Server.

**Comment by Chaphasilor** [comment]
Okay, thanks for confirming. Deselecting the library only hides it from the menu/drawer, it doesn't prevent tracks from it appearing in a playlist, artist, or instant mix.  

But I'll try to fix this sometime :)

**Comment by MattBlackOnly** [comment]
> Okay, thanks for confirming. Deselecting the library only hides it from the menu/drawer, it doesn't prevent tracks from it appearing in a playlist, artist, or instant mix.
> 
> But I'll try to fix this sometime :)

What about Playlists? In Jellyfin they appear as there own entity (kind of like a separate library)

I think you should be able to play any playlist no matter which library you have selected. But inversely those tracks should not show up in search or artist/albums...  just my convoluted opinion, not sure what you think

**Comment by Chaphasilor** [comment]
Yeah playlists are shown in all libraries and load all included tracks, no matter which library is active. This is already how Finamp does things :)
