### ISSUE TITLE
[Feature Request] Show disc and track number when viewing albums

### ISSUE THREAD

**Issue by bambadon** [UnicornsOnLSD/finamp#80]
It would be nice if Finamp would show the disc and track numbers when viewing an album. Right now you are presented a list of all the tracks, but disc and track numbers are not visible. With multi disc albums this can quickly become a little chaotic. For example I want to spin disc 2, now I need to manually look up which track is the start of disc 2. With box sets this becomes a chore very quickly.

You could take the approach of the Jellyfin client (a header Disc 1, then the tracks, header Disc 2, then the tracks, and so on) or - which would be a little cleaner and I think I'd prefer it - add this info before the song titles. Right now the tracklist is composed of [album art thumbnail] [track title]. This could be changed to [album art thumbnail] [disc number] [track number] [track title] in some sort of aesthetically pleasing way. The track titles are in a bold white font, perhaps disc and track number in non-bold light grey would be nice.

ps. Thank you for your work on this great app! I am very happy user.

**Comment by rom4nik** [comment]
@bambadon: in #129 I've added disc headers using the first form you've suggested. I've been tinkering with adding the numbers as a part of song tile, but IMHO they added a bit too much clutter and were easier to miss while scrolling quickly. Let me know what you think.
