### ISSUE TITLE
[Feature Request] Fire OS support

### ISSUE THREAD

**Issue by podulator** [UnicornsOnLSD/finamp#84]
I just tried to run this on my fire stick 4k, because it looks great ! It hangs on launch with a grey screen. 
Happy to run tests, if it is useful, to get this working on fire tv sticks

**Comment by UnicornsOnLSD** [comment]
Finamp really isn't meant for use on TVs, I don't think TV remote controls even work with it. I recommend you use some other client, such as Kodi with the Jellyfin addon.

**Comment by UnicornsOnLSD** [comment]
Closing this as TV support is out-of-scope for Finamp. The Android TV client works well for music, but I don't know if it works on Fire stuff.
