### ISSUE TITLE
[Bug] Problems with random song button

### ISSUE THREAD

**Issue by v72nico** [UnicornsOnLSD/finamp#86]
I'm on ios. The random song button always gives the same song order. Also for people with larger collections the random button slows down the app substantially, maybe it could limit the size of the random playlist to like 100 songs.

**Comment by drazil100** [comment]
I am also on iOS and aside from the first song the rest of the songs are randomized. Are you talking about the play queue showing in the same order as the album/playlist? #75

Also I don't have any lag whatsoever with my largest album's/playlists.

I am on iPhone SE 2020
My largest album/playlist is 268 songs

What device are you using and how many songs are you trying to shuffle at once?

**Comment by UnicornsOnLSD** [comment]
This is likely related to #75 and will probably be fixed when I fix that. As for large collections, I could add a limit to the amount of songs added. I could also make it configurable for those who want to get more/less songs in their queue.

**Comment by v72nico** [comment]
Thanks for the replies. I think you guys are referring to the album or playlist shuffle. I’m talking about the blue shuffle button at the bottom right corner of the songs page.

I just checked and all the songs are in the same order each time I click it not just the first one. Because this shuffles my entire collection it adds thousands of songs to the playlist.

**Comment by UnicornsOnLSD** [comment]
Yeah, I know what you mean. They use the same system for shuffling so the fix should help both.

**Comment by UnicornsOnLSD** [comment]
Also, I can recreate the slowdown on my iPhone 6

**Comment by UnicornsOnLSD** [comment]
Added configurable limit to amount of items in queue all in 4ce3185629e1d200ebbd0f75cecf200ec090db3d

**Comment by UnicornsOnLSD** [comment]
Shuffle fix in 4814a88, I'll test on iOS in a bit

**Comment by UnicornsOnLSD** [comment]
It didn't work on iOS, assuming it's a bug with the audio package. The shuffle all button gets shuffled items from Jellyfin now, so it's properly random there anyway.

**Comment by drazil100** [comment]
> The shuffle all button gets shuffled items from Jellyfin now
Does this work in offline mode?

**Comment by UnicornsOnLSD** [comment]
Good point, added 3549cb6 to shuffle songs retrieved in offline mode. This commit also makes it so that shuffle all uses the song load limit that online mode uses, which may help people with thousands of songs.

**Comment by erwinlagu** [comment]
solved?
