### ISSUE TITLE
Sleeptimer

### ISSUE THREAD

**Issue by tstelzle** [UnicornsOnLSD/finamp#94]
I would like as a new feature a sleep timer. This should just stop the music after a set time. 

Would love to see this feature!

**Comment by UnicornsOnLSD** [comment]
Good idea, that shouldn't be too hard to add :)

**Comment by Maxplosion** [comment]
especially useful, if audiobook support might be there in the future

**Comment by tstelzle** [comment]
I alraedy have all my audibooka on jellyfin. I have two libraries one of thesw only holds audiobooks. Most of them are already on muaicbrainz, which the view also pretty nice. 
Hence the sleeptimer feature would help me a lot.

**Comment by UnicornsOnLSD** [comment]
Added in b16c354
