### ISSUE TITLE
[Bug] Cannot seek the track when transcoding is enabled

### ISSUE THREAD

**Issue by Extarys** [UnicornsOnLSD/finamp#96]
I looked but I don't think it was reported.

**What is currently happening**
When I enable the transcoding option, I cannot seek in the track itself even if the whole track is already buffered not on what is currently buffered (gray bar)

The buffer gets emptied and the track restarts from the beginning.

**What should be happening**
Track is skipped to desired time.

(You might be already aware of this but it's good to make issues for follow-up etc)

**Comment by UnicornsOnLSD** [comment]
This is a known issue and it's noted in the README. I'm going to look into fixing it for the next release.

**Comment by Extarys** [comment]
Oh! :joy: Very sorry, I only looked in the issues, my bad!

**Comment by UnicornsOnLSD** [comment]
This is fixed in the new release :)
